spring:
  application:
    name: mall-gateway
  cloud:
    nacos:
      server-addr: nacos-service.infrastructure.svc.cluster.local
      username: ${NACOS_USERNAME}
      password: ${NACOS_PASSWORD}
      config:
        enabled: true
        namespace: ${NACOS_NAMESPACE}
        group: DEFAULT_GROUP
        refresh-enabled: true
      discovery:
        enabled: true
        register-enabled: false
        namespace: ${NACOS_NAMESPACE}
        group: DEFAULT_GROUP

  config:
    import:
      - nacos:mall-gateway-config.yaml

management:
  endpoint:
    health:
      show-details: never
  endpoints:
    web:
      exposure:
        include: health,info,metrics